In [102]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [103]:
scalar = torch.tensor(7)
print(scalar)
scalar.ndim
scalar.item()

tensor(7)


7

In [104]:
vector = torch.tensor([3, 6])
print(vector)
print(vector.ndim)
vector.shape

tensor([3, 6])
1


torch.Size([2])

In [105]:
MATRIX = torch.tensor([[1, 2], [3, 4]])
print(MATRIX)
print(MATRIX.ndim)
MATRIX.shape

tensor([[1, 2],
        [3, 4]])
2


torch.Size([2, 2])

In [106]:
TENSOR  = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]],[[1,2,3], [4,5,6], [7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[1][2][2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([2, 3, 3])
tensor(9)


In [107]:
random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.6419, 0.0442, 0.5775, 0.0069],
        [0.1745, 0.6012, 0.2518, 0.3078],
        [0.4542, 0.3341, 0.5364, 0.7239]])


In [108]:
random_image_size_tensor = torch.rand(224, 224, 3)
print(random_image_size_tensor.shape)
random_image_size_tensor.dtype

torch.Size([224, 224, 3])


torch.float32

In [109]:
zeros = torch.zeros(3, 4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [110]:
multi_zeros = zeros * random_tensor
multi_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [111]:
multi_zeros.dtype

torch.float32

In [112]:
range_tensor = torch.arange(0,10, 2.0)
zeros_range = torch.zeros_like(range_tensor)
zeros_range.dtype


torch.float32

In [113]:
float32_tensor = torch.tensor([2,3,4],
                              dtype = torch.float32,
                              device = None,
                              requires_grad = False)

print(f"float32_tensor.device = {float32_tensor.device}")

float32_tensor.device = cpu


In [114]:
tensor1 = torch.tensor([[2, 4],
                        [1, 4],
                        [4, 5]])
tensor2 = torch.tensor([[1, 4],
                        [1, 3],
                        [3, 4]])
print(torch.mm(tensor1, tensor2.T))
print(torch.mm(tensor1.T, tensor2))
tensor1.size


tensor([[18, 14, 22],
        [17, 13, 19],
        [24, 19, 32]])
tensor([[15, 27],
        [23, 48]])


<function Tensor.size>

In [115]:
tensor2.argmax()

tensor(1)

In [116]:
reshaped = tensor1.reshape(2,3)
reshaped == tensor1.T
print(reshaped)
print(tensor1.T)

tensor([[2, 4, 1],
        [4, 4, 5]])
tensor([[2, 1, 4],
        [4, 4, 5]])


In [118]:
z = tensor1
stack=torch.stack([z,z,z,z])
tensor3 = torch.tensor([[[1,2,],[1,2],[1,2],[1,2]]])
squeezed = torch.squeeze(tensor3)
print(squeezed.shape)
print(tensor3.shape)
unsqueezed = torch.unsqueeze(squeezed, 0)
print(unsqueezed.shape)

torch.Size([4, 2])
torch.Size([1, 4, 2])
torch.Size([1, 4, 2])


In [130]:
one_to_ten = torch.arange(1,11)
one_to_ten = one_to_ten.reshape(2,5)
print(one_to_ten)
print(one_to_ten[:, 1])
print(one_to_ten[1, :])



tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([2, 7])
tensor([ 6,  7,  8,  9, 10])


In [135]:
import torch
import numpy as np
array = np.arange(1.0, 3.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2.]), tensor([1., 2.], dtype=torch.float64))

In [137]:
RANDOM_SEED = 626
torch.manual_seed(RANDOM_SEED)
print(torch.rand(2,3))
torch.manual_seed(RANDOM_SEED)
print(torch.rand(2,3))
torch.manual_seed(RANDOM_SEED)
print(torch.rand(2,3))
seeded_random = torch.rand(2,3)

tensor([[0.5065, 0.6106, 0.4813],
        [0.2181, 0.6243, 0.3754]])
tensor([[0.5065, 0.6106, 0.4813],
        [0.2181, 0.6243, 0.3754]])
tensor([[0.5065, 0.6106, 0.4813],
        [0.2181, 0.6243, 0.3754]])


In [2]:
!nvidia-smi

Wed Feb 28 18:55:22 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
import torch
torch.cuda.is_available()

True

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')